### ISSUE TITLE
Error when parsing transaction with a ibc ack message and missing ledger record

### ISSUE THREAD

**Issue by nullpointer0x00** [provenance-io/explorer-service#500]
## Summary of Bug

This error is caused when parsing an Ibc Acknowledge message.  It tries to look up a message from a the ibc ledger table that is not there.  

```
 height  | retried | success |                                                                         error_block
----------+---------+---------+--------------------------------------------------------------------------------------------------------------------------------------------------------------
 18593830 | t       | f       | io.provenance.explorer.domain.exceptions.InvalidArgumentException: No matching IBC ledger record for channel transfer/channel-70, sequence 53447            +
          |         |         |         at io.provenance.explorer.service.async.AsyncCachingV2$saveIbcChannelData$1.invoke(AsyncCachingV2.kt:672)                                           +
          |         |         |         at io.provenance.explorer.service.async.AsyncCachingV2$saveIbcChannelData$1.invoke(AsyncCachingV2.kt:590)                                           +
          |         |         |         at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:215)           +
          |         |         |         at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)      +
          |         |         |         at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:241)      +
          |         |         |         at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:249)+
          |         |         |         at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:240)               +
          |         |         |         at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:190)                +
          |         |         |         at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:249)+
          |         |         |         at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:160)                         +
          |         |         |         at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:146)                         +
          |         |         |         at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:145)                 +
          |         |         |         at io.provenance.explorer.service.async.AsyncCachingV2.saveIbcChannelData(AsyncCachingV2.kt:590)                                                    +
          |         |         |         at io.provenance.explorer.service.async.AsyncCachingV2.addTxToCache(AsyncCachingV2.kt:311)                                                          +
          |         |         |         at io.provenance.explorer.service.async.AsyncCachingV2.addTxToCacheWithTimestamp(AsyncCachingV2.kt:294)                                             +
          |         |         |         at io.provenance.explorer.service.async.AsyncCachingV2.tryAddTxs(AsyncCachingV2.kt:281)                                                             +
          |         |         |         at io.provenance.explorer.service.async.AsyncCachingV2.addTxsToCache(AsyncCachingV2.kt:264)                                                         +
          |         |         |         at io.provenance.explorer.service.async.AsyncCachingV2.saveTxs(AsyncCachingV2.kt:226)                                                               +
          |         |         |         at io.provenance.explorer.service.async.AsyncCachingV2.saveBlockEtc(AsyncCachingV2.kt:196)                                                          +
          |         |         |         at io.provenance.explorer.service.async.AsyncCachingV2.saveBlockEtc$default(AsyncCachingV2.kt:177)                                                  +
          |         |         |         at io.provenance.explorer.service.async.AsyncService.updateLatestBlockHeightJob(AsyncService.kt:146)                                                +
          |         |         |         at jdk.internal.reflect.GeneratedMethodAccessor569.invoke(Unknown Source)                                                                           +
          |         |         |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)                                                               +
          |         |         |         at java.base/java.lang.reflect.Method.invoke(Unknown Source)                                                                                        +
          |         |         |         at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)                                              +
          |         |         |         at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)                              +
          |         |         |         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)                                                                    +
          |         |         |         at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)                                                                            +
          |         |         |         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)                                               +
          |         |         |         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)                                                                      +
          |         |         |         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)                                                                     +
          |         |         |         at java.base/java.lang.Thread.run(Unknown Source)                                                                                                   +
```

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by vwagner** [comment]
Noticing this is still a bug. Block 27975090 has an IBC client update and an ack. Explorer says there are no tx in the block

https://explorer.test.provenance.io/block/27975090

![Image](https://github.com/user-attachments/assets/8c9f13a8-4053-49f7-8447-71d499f66b97)

Query shows there are indeed tx in the block:

```
provenanced --testnet --node https://rpc.test.provenance.io:443 q block --type=height 27975090

data:
  txs:
  - CvQzCoQZCiMvaWJjLmNvcmUuY2xpZW50LnY...
```

**Comment by nullpointer0x00** [comment]
The above ibc shouldn't have caused this block collection to fail, because we are catching the error and logging it into a table.  https://github.com/provenance-io/explorer-service/blob/03df665b1aebe4d7f8ef3d745b11885b122f0241/service/src/main/kotlin/io/provenance/explorer/service/async/BlockAndTxProcessor.kt#L295  
Perhaps, the insert to the database failed?

Note: If any one of these save* methods inside processAndSaveTransaction method fails.  The whole collection of the whole block fails. https://github.com/provenance-io/explorer-service/blob/03df665b1aebe4d7f8ef3d745b11885b122f0241/service/src/main/kotlin/io/provenance/explorer/service/async/BlockAndTxProcessor.kt#L288. Fixing and improving this was documented here: https://github.com/provenance-io/explorer-service/issues/538.

**Comment by vwagner** [comment]
I'm noticing that the tx doesn't parse/display in Explorer either.

Example: height `27988407` txhash `DE47D2A150C137B3BC91BDF52DA9FE42CDDFE317B76917B75DE1138E31D85567`

https://explorer.test.provenance.io/tx/DE47D2A150C137B3BC91BDF52DA9FE42CDDFE317B76917B75DE1138E31D85567

<img width="1236" alt="Image" src="https://github.com/user-attachments/assets/a67f19de-8534-46cb-b4ba-b63fea0dccff" />

```
 testnet q tx DE47D2A150C137B3BC91BDF52DA9FE42CDDFE317B76917B75DE1138E31D85567
code: 0
codespace: ""
data: 122D0A2B2F6962632E636F72652E636C69656E742E76312E4D7367557064617465436C69656E74526573706F6E736512300A2A2F6962632E636F72652E6368616E6E656C2E76312E4D7367526563765061636B6574526573706F6E73651202080212300A2A2F6962632E636F72652E6368616E6E656C2E76312E4D7367526563765061636B6574526573706F6E736512020802
events:
- attributes:
  - index: true
    key: spender
    value: tp14hydm4wahdw7jnp4a2w3wttwucuragvcx5hkv0
  - index: true
    key: amount
    value: 8517464550nhash
  type: coin_spent
  ...
```
